### ISSUE TITLE
Model is not renderized if present in Assets. Works only on remote GLB. Tested in Debug Mode Android APILEVEL 33

### ISSUE THREAD

**Issue by antogalli** [babakcode/o3d#3]
As the title, using a local asset, the plugin renderize nothing. @babakcode

**Comment by babakcode** [comment]
Dear @antogalli, Please send me a DM in the telegram with the link below.
https://t.me/babakcode

**Comment by jQuera** [comment]
I have the same problem but with Android Emulator, on Real Device works like charm (Android 34, Flutter 3.22.2)
